# Generated by Django 4.2.2 on 2023-08-11 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_fitproduct_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitproduct',
            name='image',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pdt_img')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.fitproduct')),
            ],
        ),
    ]
