# Generated by Django 4.2.2 on 2023-08-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_fitproduct_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitproduct',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
    ]
