# Generated by Django 4.2.2 on 2023-08-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_fitproduct_is_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitproduct',
            name='short_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitproduct',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
