# Generated by Django 4.2.2 on 2023-08-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_user_id_cart_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='slug',
        ),
    ]
