# Generated by Django 4.2.2 on 2023-08-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_order_billing_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
