# Generated by Django 4.2.2 on 2023-08-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_wishlistitem_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('expired_date', models.DateField()),
                ('discount_price', models.CharField(max_length=30)),
                ('is_percentage', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
