# Generated by Django 4.2.2 on 2023-09-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitproduct',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
