# Generated by Django 4.2.2 on 2023-09-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_order_refferal_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
