# Generated by Django 4.2.2 on 2023-09-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_orderitem_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category_offer_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='category_offer_name',
            field=models.TextField(null=True),
        ),
    ]
