# Generated by Django 4.2.2 on 2023-09-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_order_category_offer_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
