# Generated by Django 4.2.2 on 2023-09-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='message',
            field=models.TextField(default='default test message'),
        ),
    ]
