# Generated by Django 4.2.2 on 2023-09-25 07:24

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_address_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phoneNumber',
            field=models.CharField(validators=[accounts.models.validate_phone_number]),
        ),
    ]
